import sys
from pathlib import Path

import h5py
import numpy as np

# Setup path
current_file = Path(__file__).resolve()
project_root = current_file.parent.parent.parent
sys.path.append(str(project_root))

from src.config import PROCESSED_DIR
from src.processing.features.engineering import FeatureEngineer


def test_feature_engineering_on_processed_data():
    print("==========================================")
    print("   TESTING FEATURE ENGINEER (REAL DATA)   ")
    print("==========================================")

    # 1. Locate the file generated by the previous test
    input_dir = PROCESSED_DIR / "test_output"
    files = list(input_dir.glob("processed_*.hdf5"))

    if not files:
        print(f"[ERROR] No processed files found in {input_dir}.")
        print("       Please run 'test_on_real_data.py' first.")
        return

    for target_file in files:
        print(f"[INFO] Applying features to: {target_file.name}")

        # 2. Initialize and Run Engineer
        engineer = FeatureEngineer(sampling_freq=4.0)

        try:
            engineer.process_file(target_file)
            print("[SUCCESS] Feature engineering process completed.")
        except Exception as e:
            print(f"[CRITICAL] Process failed: {e}")
            return

        # 3. Validate Results
        print("\n--- Validating New Parameters ---")
        with h5py.File(target_file, 'r') as f:
            params = f['Parameters']
            keys = list(params.keys())

            # Check Derivatives
            tla_deriv = "DELTA_TLA1"
            if tla_deriv in keys:
                data = params[tla_deriv][:]
                print(f"[PASS] Found {tla_deriv}. Shape: {data.shape}")
                print(f"       Mean: {np.mean(data):.4f}, Max: {np.max(data):.4f}")
            else:
                print(f"[WARN] {tla_deriv} not found (maybe TLA1 was missing in source?)")

            # Check Glide Slope
            gld = "GLD_SLOPE"
            if gld in keys:
                data = params[gld][:]
                print(f"[PASS] Found {gld}. Shape: {data.shape}")
                # Basic physics check: Slope shouldn't be wildly huge (e.g. > 30 deg) for a commercial plane
                if np.max(np.abs(data)) < 45.0:
                    print("       Value range seems plausible (< 45 deg).")
                else:
                    print(f"       [WARN] Values seem extreme (Max: {np.max(data):.2f} deg).")
            else:
                print(f"[WARN] {gld} not found (missing GS_C or IVV_C?)")


if __name__ == "__main__":
    test_feature_engineering_on_processed_data()